Repository leo-daniel/do-something, pull requests merged in 2018-09, with the labels that each got.

#25 eslint + babel rc files added for repo rules
  .babelrc
  .eslintrc
  README.old.md
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/registerServiceWorker.js
  client/yarn.lock
Labels: infrastructure

#31 Component add
  components/DeleteBtn/DeleteBtn.css
  components/DeleteBtn/DeleteBtn.js
  components/DeleteBtn/index.js
  components/Form/FormBtn.js
  components/Form/Input.js
  components/Form/TextArea.js
  components/Form/index.js
  components/Grid/Col.js
  components/Grid/Container.js
  components/Grid/Row.js
  components/Grid/index.js
  components/Jumbotron/Jumbotron.js
  components/Jumbotron/index.js
  components/List/List.css
  components/List/List.js
  components/List/ListItem.js
  components/List/index.js
  components/Nav/Nav.js
  components/Nav/index.js
Labels: infrastructure

#36 Removed root components directory
  components/DeleteBtn/DeleteBtn.css
  components/DeleteBtn/DeleteBtn.js
  components/DeleteBtn/index.js
  components/Form/FormBtn.js
  components/Form/Input.js
  components/Form/TextArea.js
  components/Form/index.js
  components/Grid/Col.js
  components/Grid/Container.js
  components/Grid/Row.js
  components/Grid/index.js
  components/Jumbotron/Jumbotron.js
  components/Jumbotron/index.js
  components/List/List.css
  components/List/List.js
  components/List/ListItem.js
  components/List/index.js
  components/Nav/Nav.js
  components/Nav/index.js
  server.js
Labels: infrastructure

#42 Event model
  models/event.js
  models/index.js
  server.js
Labels: Newsfeed

#39 Map
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/LeafletMap.js
  client/src/components/leafletmap.css
  client/src/components/vol-icon.png
  client/src/index.js
  client/src/logo.svg
  client/src/pages/Main.js
  server.js
Labels: Map

#52 Map upgrade
  client/package.json
  client/src/App.js
  client/src/components/LeafletMap.js
  client/src/components/Navbar.js
  client/src/components/vol-icon.png
  client/src/pages/Map.js
  package.json
  scripts/seedDB.js
Labels: Map

#53 Material-UI Update
  client/package.json
  client/public/react.ico
  client/yarn.lock
  package.json
  yarn.lock
Labels: infrastructure

#71 Working heroku
  .env.development
  client/package.json
  config/passport/index.js
  config/passport/login.js
  config/passport/signup.js
  models/event.js
  models/index.js
  package.json
  server.js
Labels: infrastructure

#73 Updated Yarn lockfile
  yarn.lock
Labels: heroku

#76 Map style
  client/src/components/LeafletMap.js
  client/src/components/user-location.svg
  client/src/components/vol-icon.svg
Labels: Map
